### ISSUE TITLE
DXR not working, Render Pipeline Wizard can't set Default DXR scene prefab

### ISSUE THREAD

**Issue by smokelore** [keijiro/UnityDxrTest#2] opened 2020-01-09 18:36 UTC
The project did not render and raytracing when I first opened it . Some debugging led me to the Render Pipeline Wizard, which showed some things that needed fixing. One of those fixes does not work, however: Default DXR scene prefab. It throws an "ArgumentNullException" whenever I click the Fix button.

![image](https://user-images.githubusercontent.com/1188899/72094490-8ac01d80-32e4-11ea-9be6-468fa9536d69.png)

Do you have any advice about how to get this project's DXR features working?

I am using Unity 2020.1.0a18.2166 and my GPU is an RTX 2080.

Perhaps this is the wrong place to ask about this issue. If so, feel free to close this!

**Comment by mr-brooks-dev** [comment] 2020-01-09 21:03
I was just about to post with the exact same issue. Everything is the same on my end except I'm using the same editor version as the repo project: 2020.1.0a17.2089 and I'm using a GTX1080ti.  Also - I am able to successfully use DXR setup when I start from a blank project on the same machine and then install the HDRP package and configure for DXR in the HD Pipeline Wizard. Any ideas?

**Comment by keijiro** [comment] 2020-01-10 03:35
This is a known issue of Unity 2020.1.0a18 (issue 1206922).

There are two options to solve the issue:

- Downgrade to 2020.1.0a17 - unityhub://2020.1.0a17/ccc6f9131a63
- Wait for 2020.1.0.a19

**Comment by keijiro** [comment] 2020-01-10 03:37
@vjanomolee Just a wild guess but GTX might not be able to run tier2 examples. How about ShaderGraph.unity? That's the only tier1 example in this repository

**Comment by keijiro** [comment] 2020-01-15 05:12
I'm closing this issue now. Please feel free to reopen if it still reproduces.

**Closed as completed by keijiro** 2020-01-15 05:12 UTC
Labels: question

**Comment by keijiro** [comment] 2020-01-16 14:23
I confirmed that the problem is fixed in 2020.1.0a19.

**Comment by smokelore** [comment] 2020-01-17 20:21
Hey Keijiro! Sorry for the delay in my reply. 

I actually just go the opportunity to test the project in 2020.1.0a19 and I still have the same issue... I've downloaded the latest version of the project and I'm still getting the same "ArgumentNullException" error on the "Default DXR scene prefab" setting in the Render Pipeline Wizard.

I realize this is not your responsibility to fix, but I would love to get HDRP + DXR working in Unity. I appreciate your assistance so far!

**Comment by smokelore** [comment] 2020-01-17 21:35
After some testing it seems like the scenes still run despite the un-fixable Render Pipeline Wizard setting! I do not know if it is negatively affecting performance or not.

**Comment by keijiro** [comment] 2020-01-18 07:52
@smokelore Please understand that the wizard just shows some setup recommendations -- not mandatory things. I intentionally removed some unused elements, so please ignore those warnings.
